package ssm.bean;


import javax.validation.constraints.Pattern;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.last_name
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    @Pattern(regexp = "^[a-zA-Z0-9_-]{6,16}$",message = "用户名必须是6-16位的数字或者字母")
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.gender
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.email
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    @Pattern(regexp = "^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$",message = "邮箱格式不正确")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_employee.d_id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    private Integer dId;

    private Department department;

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.id
     *
     * @return the value of tb1_employee.id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.id
     *
     * @param id the value for tb1_employee.id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.last_name
     *
     * @return the value of tb1_employee.last_name
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.last_name
     *
     * @param lastName the value for tb1_employee.last_name
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.gender
     *
     * @return the value of tb1_employee.gender
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public String getGender() {

        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.gender
     *
     * @param gender the value for tb1_employee.gender
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public void setGender(String gender) {

        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.email
     *
     * @return the value of tb1_employee.email
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.email
     *
     * @param email the value for tb1_employee.email
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_employee.d_id
     *
     * @return the value of tb1_employee.d_id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_employee.d_id
     *
     * @param dId the value for tb1_employee.d_id
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", lastName='" + lastName + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                ", department=" + department +
                '}';
    }

    public Employee(Integer id, String lastName, String gender, String email, Integer dId) {
        this.id = id;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        this.dId = dId;
    }

    public Employee() {
    }
}