package ssm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;
import ssm.bean.Employee;
import ssm.bean.EmployeeExample;
public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    List<Employee> selectByExample(EmployeeExample example);




    List<Employee> selectByExampleWithDept(EmployeeExample example);
    Employee selectByPrimaryKeyWithDept(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1_employee
     *
     * @mbg.generated Tue Aug 24 09:21:20 CST 2021
     */
    int updateByPrimaryKey(Employee record);
}